spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启下划线转驼峰
